import * as LucideIcons from 'lucide-react';

const iconNameToComponent: Record<string, React.ComponentType<any>> = {
  utensils: LucideIcons.Utensils,
  coffee: LucideIcons.Coffee,
  car: LucideIcons.Car,
  bus: LucideIcons.Bus,
  train: LucideIcons.Train,
  plane: LucideIcons.Plane,
  bed: LucideIcons.Bed,
  home: LucideIcons.Home,
  house: LucideIcons.House,
  building: LucideIcons.Building,
  shoppingCart: LucideIcons.ShoppingCart,
  shoppingBag: LucideIcons.ShoppingBag,
  creditCard: LucideIcons.CreditCard,
  wallet: LucideIcons.Wallet,
  film: LucideIcons.Film,
  tv: LucideIcons.Tv,
  music: LucideIcons.Music,
  book: LucideIcons.Book,
  heart: LucideIcons.Heart,
  pulse: LucideIcons.Activity,
  briefcase: LucideIcons.Briefcase,
  trendingUp: LucideIcons.TrendingUp,
  trendingDown: LucideIcons.TrendingDown,
  piggyBank: LucideIcons.PiggyBank,
  laptop: LucideIcons.Laptop,
  smartphone: LucideIcons.Smartphone,
  tablet: LucideIcons.Tablet,
  user: LucideIcons.User,
  users: LucideIcons.Users,
  baby: LucideIcons.Baby,
  pawPrint: LucideIcons.PawPrint,
  dumbbell: LucideIcons.Dumbbell,
  graduationCap: LucideIcons.GraduationCap,
  gift: LucideIcons.Gift,
  star: LucideIcons.Star,
  zap: LucideIcons.Zap,
  droplets: LucideIcons.Droplets,
  plus: LucideIcons.Plus,
  rotateLeft: LucideIcons.RotateCcw,
  rotateRight: LucideIcons.RotateCw,
  repeat: LucideIcons.Repeat,
  ellipsisHorizontal: LucideIcons.Ellipsis,
  ellipsisVertical: LucideIcons.EllipsisVertical,
  folder: LucideIcons.Folder,
  arrowRightLeft: LucideIcons.ArrowRightLeft,
};

export function getIconComponent(iconName: string): React.ComponentType<any> {
  if (!iconName) return LucideIcons.Folder;
  return iconNameToComponent[iconName] || LucideIcons.Folder;
}

export const Folder = LucideIcons.Folder;

export const availableIcons = [
  { name: 'utensils', label: 'Food', icon: LucideIcons.Utensils },
  { name: 'coffee', label: 'Coffee', icon: LucideIcons.Coffee },
  { name: 'car', label: 'Car', icon: LucideIcons.Car },
  { name: 'bus', label: 'Bus', icon: LucideIcons.Bus },
  { name: 'plane', label: 'Plane', icon: LucideIcons.Plane },
  { name: 'bed', label: 'Hotel', icon: LucideIcons.Bed },
  { name: 'home', label: 'Home', icon: LucideIcons.Home },
  { name: 'shoppingCart', label: 'Cart', icon: LucideIcons.ShoppingCart },
  { name: 'shoppingBag', label: 'Bag', icon: LucideIcons.ShoppingBag },
  { name: 'creditCard', label: 'Card', icon: LucideIcons.CreditCard },
  { name: 'wallet', label: 'Wallet', icon: LucideIcons.Wallet },
  { name: 'film', label: 'Film', icon: LucideIcons.Film },
  { name: 'music', label: 'Music', icon: LucideIcons.Music },
  { name: 'book', label: 'Book', icon: LucideIcons.Book },
  { name: 'heart', label: 'Health', icon: LucideIcons.Heart },
  { name: 'pulse', label: 'Medical', icon: LucideIcons.Activity },
  { name: 'briefcase', label: 'Work', icon: LucideIcons.Briefcase },
  { name: 'trendingUp', label: 'Growth', icon: LucideIcons.TrendingUp },
  { name: 'piggyBank', label: 'Savings', icon: LucideIcons.PiggyBank },
  { name: 'laptop', label: 'Tech', icon: LucideIcons.Laptop },
  { name: 'smartphone', label: 'Phone', icon: LucideIcons.Smartphone },
  { name: 'user', label: 'User', icon: LucideIcons.User },
  { name: 'users', label: 'Group', icon: LucideIcons.Users },
  { name: 'baby', label: 'Baby', icon: LucideIcons.Baby },
  { name: 'pawPrint', label: 'Pet', icon: LucideIcons.PawPrint },
  { name: 'dumbbell', label: 'Gym', icon: LucideIcons.Dumbbell },
  { name: 'graduationCap', label: 'Education', icon: LucideIcons.GraduationCap },
  { name: 'gift', label: 'Gift', icon: LucideIcons.Gift },
  { name: 'star', label: 'Star', icon: LucideIcons.Star },
  { name: 'zap', label: 'Energy', icon: LucideIcons.Zap },
  { name: 'droplets', label: 'Water', icon: LucideIcons.Droplets },
  { name: 'plus', label: 'Add', icon: LucideIcons.Plus },
  { name: 'rotateLeft', label: 'Undo', icon: LucideIcons.RotateCcw },
  { name: 'repeat', label: 'Repeat', icon: LucideIcons.Repeat },
  { name: 'ellipsisHorizontal', label: 'More', icon: LucideIcons.Ellipsis },
  { name: 'folder', label: 'Other', icon: LucideIcons.Folder },
];
